version: 0.2
phases:
  pre_build:
    commands:
      - usermod -s /bin/bash www-data
      - cat /etc/passwd
      - echo "ENV"
      - env
      - echo "PWD"
      - pwd
      - echo
      - apt update
      - apt -y install libx11-xcb1 libxtst6 libnss3 libasound2 libatk-bridge2.0-0 libgtk-3-0
      - npm install
      - chown -R www-data:www-data .
  build:
    run-as: 'www-data'
    commands:
      - npm run build
      - ls -la
      - whoami
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: public
