version: 0.2
phases:
  pre_build:
    commands:
      - cat /proc/version
      - uname -a
      - usermod -s /bin/bash www-data
      - cat /etc/passwd
      - echo "ENV"
      - env
      - echo "PWD"
      - pwd
      - echo
      # - apt update
      # - apt -y install libx11-xcb1 libxtst6 libnss3 libasound2 libatk-bridge2.0-0 libgtk-3-0
      - apt-get upgrade
      - apt-get update
      # apt-get install -y libxcursor1 libgtk-3-dev libxss1 libasound2 libnspr4 libnss3 libx11-xcb1
      - apt-get install -y libx11-xcb1 libxtst6 libnss3 libasound2 libatk-bridge2.0-0 libgtk-3-0
      # sysctl kernel.unprivileged_userns_clone=1
      # sysctl -w kernel.userns_restrict=0
      - npm install
      - chown -R www-data:www-data .
      - chown -R www-data:www-data /root/
  build:
    run-as: 'www-data'
    commands:
      - npm run build
      - ls -la *
      - whoami
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: public
