version: 0.2
phases:
  pre_build:
    commands:
      - apt update
      - apt -y install libx11-xcb1 libxtst6 libnss3 libasound2 libatk-bridge2.0-0
      - npm install
  build:
    commands:
      - npm run build
      - ls -la public/
